include:
  # `include` is like a copy-paste, so `docker compose up` in this directory should start
  # all of these automatically (that match the right profile)
  - ./proxy/nginx/compose.yaml
  - ./proxy/iocaine/compose.yaml
  - ./services/personal_website/compose.yaml
  - ./services/mail_server/compose.yaml
