# yes, i know the `env_file` key under `include` exists for docker compose to pass multiple
# `.env` files to a compose.yaml, but the relative paths appear to catastrophically fuck up
# whenever there are recursive includes, and i also have to manually keep track of them
# when passing `--env-file` to run those subcontainers alone as well. this has caused me
# a frankly cruel amount of pain and i have become a docker compose hater for life.
# LET ME FUCKING DECLARE THE .ENV FILES FOR A COMPOSE.YAML'S OWN INTERPOLATION **IN ITS OWN FILE**
# YOU FUCKING GREASY PIECE OF SHIT
# FUCK YOU

#!/usr/bin/env bash

set -e

shopt -s globstar

# this makes sure that this script always runs in its own directory so that it pulls
# the right `.env`, for instance (this should also be an absolute path)
script_path="$(dirname "$(realpath "${BASH_SOURCE[0]:-$0}")")"
cd "$script_path"

source ./.env

function upsertLine {
    file="$1"
    replace_pattern="$2"
    replacement_line="$3"
    is_first_appended_line="$4"

    is_found='false'
    while IFS= read -r line; do
        if [[ "$line" == *"$replace_pattern"* ]]; then
            echo "$replacement_line"
            is_found='true'
        else
            echo "$line"
        fi
    done < "$file" > "$file.tmp" && mv "$file.tmp" "$file"

    if [[ "$is_found" == "false" ]]; then
        (
            if [[ "$is_first_appended_line" == "true" ]]; then
                echo ''
                echo '# automatically generated by `sync_dotenvs.sh`'
            fi
            echo "$replacement_line"
        ) >> "$file"
    fi
}

for file in **/.env; do
    # check in case of empty glob
    if [[ -f "$file" ]]; then
        upsertLine "$file" \
            "DOCKER_DEFAULT_PROFILE" "DOCKER_DEFAULT_PROFILE=$DOCKER_DEFAULT_PROFILE" "true"
        upsertLine "$file" \
            "DOCKER_ROOT_USER" "DOCKER_ROOT_USER=$DOCKER_ROOT_USER" "false"
        upsertLine "$file" \
            "DOCKER_NONROOT_USER" "DOCKER_NONROOT_USER=$DOCKER_NONROOT_USER" "false"
        upsertLine "$file" \
            "HOST_NONROOT_UID" "HOST_NONROOT_UID=$HOST_NONROOT_UID" "false"
    fi
done
